### ISSUE TITLE
How To Contribute

### ISSUE THREAD

**Issue by ZenMaxe** [Chillu1/ModiBuff#19]
I'm interested in contributing to this project, but I've noticed there aren't any contribution guidelines available in the repository. To help new contributors (like myself) and to standardize the contribution process, it would be beneficial to have a CONTRIBUTING.md guide.

**Comment by Chillu1** [comment]
Hey, thanks. I've added a basic [CONTRIBUTING file](https://github.com/Chillu1/ModiBuff/blob/master/CONTRIBUTING.md), can you give a comment on it?

I have a rather big TODO list in the back, and wanted to transform all the "sure" TODOs to GH issues. But writing them out takes some time, so I only added a few important ones so far.

I also wanted to add a few "good first issue" issues, but these were hard to come by, since most of the "easy" functionality is already implemented. But I think I might have a few. Especially adding some kind of very basic samples/examples in Unity or Godot. Good way to learn the library, while also contributing.
